import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Container from "~/components/container";
import VehicleCard from "~/components/vehicle/vehicle-card";
import { type Vehicle } from "~/server/api/routers/vehicles";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const userId = String(user.user?.id);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [loading, setLoading] = useState(true);

  const { data, status } = api.vehicles.getVehiclesByUser.useQuery(userId);

  if (data?.length && vehicles !== data) {
    setVehicles(data as Vehicle[]);
    setLoading(false);
  }

  if (userId && status === "success" && !data) {
    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container loading={loading}>
          {!!user.isSignedIn && <p>Hello {user.user.fullName}</p>}

          {vehicles && vehicles.length === 0 && (
            <p>
              You don&apos;t have a vehicle.{" "}
              <Link href="/vehicles/add" className="text-blue-400 underline">
                Add one
              </Link>
            </p>
          )}
          {vehicles && vehicles.length > 0 && (
            <>
              <h3>Your vehicles</h3>
              {vehicles.map((vehicle) => (
                <VehicleCard key={vehicle.id} vehicle={vehicle} />
              ))}
            </>
          )}
        </Container>
      </main>
    </>
  );
}
