import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data } = api.vehicles.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1>Sign in</h1>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>{JSON.stringify(data)}</div>
        {data && <div>{data.map((vehicle) => vehicle.model)}</div>}
      </main>
    </>
  );
}
